source("/home/mich/Documents/steam-insights/r_scripts/d/a.r")
#print("a.r finished")
#fig <- plot_ly(df, y = df$publisher ~ df$total, type='box')
#print("figure plotted")
#print(fig)
#print("printed figure")
new_fig <- plot_ly(df, y = ~total, x = ~publishers, text = ~review_score, textposition = 'auto', mean = means, type = "box", boxpoints = 'suspectedoutliers')
print(new_fig)